sudo: required
services:
    - docker

before_install:
    - docker build -t morrita123/docker-react -f Dockerfile.dev .

script:
    - docker run morrita123/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-2-589716606524"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
